Music/config/routes.rb
Rails.application.routes.draw do
  resources :users, only:[:create, :new, :show]
  resource :session, only:[:create, :new, :destroy]

end

Music/app/models/album.rb
class Album < ActiveRecord::Base
end

Music/app/models/band.rb
class Band < ActiveRecord::Base
end

Music/app/models/track.rb
class Track < ActiveRecord::Base
end

Music/app/models/user.rb
class User < ActiveRecord::Base

  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password
  after_initialize :ensure_session_token

  def self.generate_session_token
    SecureRandom.urlsafe_base64(128)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end
end

Music/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login(user)
    session[:session_token] = user.session_token
  end

  def logout
    if current_user
      current_user.reset_session_token!
      session[:session_token] = nil
    end
  end

end

Music/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
                session_params[:email],
                session_params[:password]
    )
    if user
      login(user)
      redirect_to user_url(user)
    else
      redirect_to new_session_url
    end
  end


  def destroy
    logout
    render :new
  end

  private

  def session_params
    params.require(:user).permit(:email, :password)
  end

end

Music/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.new(user_params)
    if user.save
      login(user)
      redirect_to user_url(user)
    else
      redirect_to new_user_url
    end
  end

  def show
    # if current_user.id == params[:id].to_i
      @user = current_user
      render :show
    # else
    #   redirect_to new_user_url
    # end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

Music/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input type = 'hidden'
            name = 'authenticity_token'
            value = '#{form_authenticity_token}'>".html_safe
  end

end

Music/app/helpers/sessions_helper.rb
module SessionsHelper
end

Music/app/helpers/users_helper.rb
module UsersHelper
end

Music/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Music</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<% if current_user %>
    <%= button_to "Logout", session_url, method: :delete  %>
<% else %>
    <%= button_to "Login Page", new_session_url, method: :get  %>
<% end %>
<body>

<%= yield %>

</body>
</html>

Music/app/views/users/new.html.erb
<h1> Create New User </h1>

<form action= "<%= users_url  %>" method="post">

  <label for="email"> Email </label>
    <input type="text" name="user[email]" id="email">

    <br>
    <br>

  <label for="password"> Password (6 chars or more) </label>
    <input type="text" name="user[password]" id="password">

    <br>
    <br>
    <input type="submit" value="Create New User">

    <%= auth_token %>
</form>

Music/app/views/users/show.html.erb
<h2> Welcome, <%= @user.email %></h2>